Attention Mechanism

In [1]:
import numpy as np
from scipy.special import softmax

In [2]:
# Input Embedding 3 inputs with dm=4

x = np.array([[1.0, 0.0, 1.0, 0.0],
             [0.0, 2.0, 0.0, 2.0],
             [1.0, 1.0, 1.0, 1.0]])

In [3]:
# Weights should be dk,dm 

w_query = np.array([[1,0,1],
                    [1,0,0],
                    [0,0,1],
                    [0,1,1]])

w_key = np.array([[0,0,1],
                 [1,1,0],
                 [0,1,0],
                  [1,1,0]])

w_value = np.array([[0,2,0],
                   [0,3,0],
                   [1,0,3],
                   [1,1,0]])

In [4]:
Q = np.matmul(x, w_query)
K = np.matmul(x, w_key)
V = np.matmul(x, w_value)

In [13]:
# square root of dk = 1
attention_scores = Q @ K.T

In [14]:
attention_scores[0]=softmax(attention_scores[0])
attention_scores[1]=softmax(attention_scores[1])
attention_scores[2]=softmax(attention_scores[2])
print(attention_scores[0])
print(attention_scores[1])
print(attention_scores[2])

[0.06337894 0.46831053 0.46831053]
[6.03366485e-06 9.82007865e-01 1.79861014e-02]
[2.95387223e-04 8.80536902e-01 1.19167711e-01]


In [16]:
attention_scores[0].reshape(-1,1)[0][0]

0.06337893833303762

In [19]:
attention1=attention_scores[0].reshape(-1,1)
attention1=attention_scores[0][0]*V[0]
print(attention1)

print("Attention 2")
attention2=attention_scores[0][1]*V[1]
print(attention2)

print("Attention 3")
attention3=attention_scores[0][2]*V[2]
print(attention3)

[0.06337894 0.12675788 0.19013681]
Attention 2
[0.93662106 3.74648425 0.        ]
Attention 3
[0.93662106 2.80986319 1.40493159]
